### ISSUE TITLE
Getting 414 when getting back from eway

### ISSUE THREAD

**Issue by ankitladhania** [webaware/gravityforms-eway#1]
Hi @webaware,
I'm getting 414 on all the response from eway. here is a sample url:
http://localhost/?__gfewayproreturn=eyJpZCI6IjMxNjciLCJ0eG4iOiI1ZDU0ZDljZTk5YzVkIn0JNTA2ZjM3NGMwNzU0OWQwZTQ1NTU3ZDYzZDhmZjkzNTM&AccessCode=60CF3JlqbWR09KBzcpdE41EZ24S2EV4jjHiZTZ5PEwcmWdDqbxa2tPV_eh7362Quxqhl5uJMP7nibqVrqnBv-ZG_PlS1y4owJtTO0YdSgTruXwnJLjNcMrjkJgAWjyApY_WIL

PFA the Image
https://i.ibb.co/bsc52cB/Screenshot-2019-08-15-at-10-37-19-AM.png

**Comment by webaware** [comment]
It looks like you have a really small limit on request length in your Apache config -- `LimitRequestLine`. Either remove the limit so that the default 8190 kicks in, or set it to 8190 (or something big enough):

http://httpd.apache.org/docs/2.2/mod/core.html#limitrequestline
